WebCRM/Controllers/CheckController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data.Entity;
using WebCRM.Data;
using WebCRM.Interfaces;
using WebCRM.Models;
using WebCRM.Repository;

namespace WebCRM.Controllers
{
    public class CheckController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CheckController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public  IActionResult Index()
        {
            IEnumerable<Check> checks = _context.Checks.ToList();

            return View(checks);
        }
        
        [HttpPost]
        public  IActionResult Delete(int id)
        {
            if (id != null && id > 0)
            {
                var check = _context.Checks.Find(id);
                _context.Checks.Remove(check);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

WebCRM/Controllers/ProfitController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebCRM.Data;
using WebCRM.Models;
using WebCRM.Views;
using DataPoint = WebCRM.Views.DataPoint;

namespace WebCRM.Controllers
{
    public class ProfitController : Controller
    {
		private readonly ApplicationDbContext _context;
        public ProfitController(ApplicationDbContext context)
        {
				_context = context;
        }
        public ActionResult Index()
		{
			
			List<DataPoint> dataPoints = new List<DataPoint>();
			IEnumerable<Check> checks = _context.Checks.ToList();
			dataPoints.Add(new DataPoint("Initial", 0));
			foreach (Check check in checks)
			{

				int i = 0;
				dataPoints.Add(new DataPoint(check.Created.ToLongDateString(), Convert.ToDouble(Cart.CartHistory[i])));
				i++;
				
			}
			dataPoints.Add(new DataPoint("Final", true, "{y}"));

			ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);

			return View();
		}

		
	}

}

WebCRM/Controllers/SellController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Text.Json;
using WebCRM.Data;
using WebCRM.Interfaces;
using WebCRM.Models;
using WebCRM.Repository;

namespace WebCRM.Controllers
{
    public class SellController : Controller
    {
        private readonly IProductRepository _productRepositrory;
        private readonly ApplicationDbContext _context;
        private readonly ICustomerRepository _customerRepository;
        public SellController(IProductRepository productRepositrory, ApplicationDbContext context, ICustomerRepository customerRepository)
        {
            _productRepositrory = productRepositrory;
            _context = context;
            _customerRepository = customerRepository;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Product> products = await _productRepositrory.GetAll();
            return View(products);
        }
        [HttpGet("{price:decimal}")]
        public IActionResult Buy(decimal price)
        {
            Cart.AllPrice += price;
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Pay(string name)
        {
            if (name != null)
            {
                var customer = new Customer() { Name = name };
                var check = new Check
                {
                    Customer = customer,
                    Seller = _context.Sellers.FirstOrDefault(),
                    Created = DateTime.Now
                };
                _customerRepository.Add(customer);
                _context.Checks.Add(check);
                _context.SaveChanges();
                Cart.CartHistory.Add(Cart.AllPrice);
                Cart.AllPrice = 0;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        } 
    }
}

WebCRM/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebCRM.Data;
using WebCRM.Interfaces;
using WebCRM.Models;
using WebCRM.Views.Account;

namespace WebCRM.Controllers
{
    public class UserController : Controller
    {
        //private readonly UserManager<AppUser> _userManager;
        //private readonly ApplicationDbContext _context;
        private readonly IUserRepository _userRepository;


        public UserController(IUserRepository userRepository)
        {
            //_userManager = userManager;
            //_context = context;
            _userRepository = userRepository;
        }
        [HttpGet("users")]
        public IActionResult Index()
        {
            IEnumerable<AppUser> users = _userRepository.GetAll();
            return View(users);
        }
        [HttpGet("{email}")]
        public async Task<IActionResult> Delete(string email)
        {
            if (email != null)
            {
                var user = _userRepository.GetByEmail(email);
                _userRepository.Remove(await user);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }

}

WebCRM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCRM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebCRM.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebCRM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Seller" asp-action="Index">Sellers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sell" asp-action="Index">Seels</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Check" asp-action="Index">Checks</a>
                            </li>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Profit" asp-action="Index">Profit</a>
                                </li>
                            }
                            <li class="nav-item">
                                <form asp-area="" asp-controller="Account" asp-action="Logout">
                                    <button class="btn btn-outline-danger">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Sign up</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebCRM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>