WebCRM/Models/Seller.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebCRM.Models
{
    public class Seller
    {
        [Key]
        public int Id { get; set; }

        public string? Name { get; set; }

        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }

        public ICollection<Check>? Checks { get; set; }
        public override string ToString()
        {
            return Name;
        }
    }
}

WebCRM/Controllers/SellerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WebCRM.Data;
using WebCRM.Interfaces;
using WebCRM.Models;
using WebCRM.Repository;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace WebCRM.Controllers
{
    public class SellerController : Controller
    {
        private readonly ISellerRepository _sellerRepository;

        public SellerController(ISellerRepository sellerRepository)
        {
            _sellerRepository = sellerRepository;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Seller> sellers = await _sellerRepository.GetAll();
            return View(sellers);
        }
        public IActionResult SellerAdd(Seller model)
        {
            if (model.Name != null)
            {
                _sellerRepository.Add(model);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        }
        [HttpPost]
        public IActionResult SellerDelete(int id)
        {
            var seller = _sellerRepository.GetById(id);
            if (seller != null)
            {
                _sellerRepository.Remove(seller);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult SellerEdit(int id, Seller model)
        {
            if (_sellerRepository.Edit(model, id))
                return RedirectToAction("Index");

            return RedirectToAction("Index");
        }
        
    }
}

WebCRM/Views/Seller/Index.cshtml
@model IEnumerable<Seller>
@{
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 11pt;
        }

        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            background-color: #fff;
        }

            table th {
                background-color: #B8DBFD;
                color: #333;
                font-weight: bold;
            }

            table th, table td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            table, table table td {
                border: 0px solid #ccc;
            }

        .formdiv0 {
            margin-top: 30px;
        }

        .formdiv1 {
            margin-bottom: 20px;
        }

        .formdiv2 {
            margin-bottom: 20px
        }

        .formdiv3 {
            margin-bottom: 20px
        }

        .b1 {
            background: #B8DBFD;
            margin: 5px
        }

        .b2 {
            background: #B8DBFD;
            margin: 5px
        }

        .b3 {
            background: #B8DBFD;
            margin: 5px;
        }

        .body {
            background: #dae3e3;
            margin: 5px;
        }
    </style>
</head>
<body class="body">
    <h4>Customers</h4>
    <hr />
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th>CustomerID</th>
            <th>CustomerName</th>
        </tr>
        @foreach (Seller seller in Model)
        {
            <tr>
                <td>@seller.Id</td>
                <td>@seller.Name</td>
            </tr>
        }
    </table>
    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
    {
        <div class="formdiv0">
            <form asp-controller="Seller" asp-action="SellerAdd" method="post">
                <div class="formdiv1">
                    <label>Name:</label><br />
                    <input name='name' /><br />
                    <input type='submit' class="b1" value='Add' />
                </div>
            </form>
            <form asp-controller="Seller" asp-action="SellerDelete" method="post">
                <div class="formdiv2">
                    <label>Id:</label><br />
                    <input name='id' /><br />
                    <input type="submit" class="b2" value='Delete' />
                </div>
            </form>
            <form asp-controller="Seller" asp-action="SellerEdit" method="post">
                <div class="formdiv3">
                    <label>Id:</label><br />
                    <input name='id' /><br />
                    <label>Name:</label><br />
                    <input name='name' /><br />
                    <input type='submit' class="b3" value='Edit' />
                </div>
            </form>
        </div>
    }
    
</body>
</html>